name: Build and Deploy
env:
    folder: src
    token: ${{ secrets.t }}
on:
  workflow_dispatch:
  push:
  repository_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Generate Static Site🛠
        run: |
         npm install
         webpack --colors --bail
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.t }}
         publish_dir: ./build
         publish_branch: gh-pages

